### ISSUE TITLE
psycopg2 dependency too strict

### ISSUE THREAD

**Issue by sergei-maertens** [CodeYellowBV/django-relativedelta#6]
Looking at 

https://github.com/CodeYellowBV/django-relativedelta/blob/28f3db675b60125997d999b33fbf5a2124c574a1/setup.py#L43

I think this is a bit too strict. We have some projects with `psycopg2-binary` to easy dev-install, but this project is pulling in `psycopg2` as well. Can you drop that or make it an optional dep so it can be specified which psycopg2 package is used?

**Comment by sjamaan** [comment]
Hi, thanks for pointing this out. This stuff is very confusing to me. Simply changing the dependency to `psycopg2-binary` is incorrect as this may cause segfaults on some machines, if I understand the documentation and discussion correctly.

I _could_ drop the dependency because currently I'm not actually directly importing anything from psycopg2 (I think..), but that may change in the future (and the tests rely on it, anyway). I've asked the psycopg2 author for advice on what to do here, because I'd like to know the correct solution here if we ever do need to import stuff directly.

**Comment by sjamaan** [comment]
Also, note that the [official docs for Psycopg2](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi) warn against installinging from binary packages and seem to suggest that libraries should depend on the plain `psycopg2` package:

> The -binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements. If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.

So you may want to reconsider your dependency as well.

**Comment by sjamaan** [comment]
Makes one wonder when (if ever) one should be using `psycopg2-binary` in `requirements.txt` at all...

**Comment by sergei-maertens** [comment]
Yeah, it's a bit annoying and I'm updating away from psycopg-binary anyway,
but I think that removing the dependency from setup.py is the easiest
option + adding to the readme that you need it (which you already have
covered basically because it only works on postgres).

**Comment by dvarrazzo** [comment]
FYI I think this dependency specification is the right thing and `psycopg2-binary` shouldn't be mentioned in `requirements.txt`.

**Comment by sergei-maertens** [comment]
I disagree, if I have verified that psycopg2-binary works for me, then I
don't want that to be overwritten by an indirect dependency... Especially
if both options provide the exact same feature set and are drop in
replacements of each other!

**Comment by sjamaan** [comment]
Should be fixed in 1.0.5 (I moved the dependency to the `tests_require` declaration).

**Comment by sergei-maertens** [comment]
Super cool, thanks!
